/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.shop_manager.GUI.view;

import com.mycompany.shop_manager.BLL.OrderBLL;
import com.mycompany.shop_manager.GUI.ColorTheme;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.List;
import com.mycompany.shop_manager.DAL.*;
import java.sql.Date;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author Admin
 */
public class BillPayPanel extends javax.swing.JPanel {

    /**
     * Creates new form BillProductPanel
     */
    public BillPayPanel() {
        initComponents();
        
        initPayPane();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbCustomer = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cbCustomer = new javax.swing.JComboBox<>();
        Lb2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TaNote = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnPay = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TfTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TfDelPro = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        TfSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(760, 600));
        setRequestFocusEnabled(false);

        LbCustomer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LbCustomer.setText("Khách hàng");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        cbCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Lb2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Lb2.setText("Ghi chú");

        TaNote.setColumns(20);
        TaNote.setRows(5);
        jScrollPane2.setViewportView(TaNote);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sản Phẩm");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thanh Toán");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Hoá đơn");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));

        btnPay.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnPay.setText("Thanh toán +");
        btnPay.setActionCommand("Thêm vào giỏ hàng +");
        btnPay.setBorder(null);
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        btnDel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnDel.setText("Xoá sản phẩm X");
        btnDel.setActionCommand("Thêm vào giỏ hàng +");
        btnDel.setBorder(null);
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Tổng");

        TfTotal.setEditable(false);
        TfTotal.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TfTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfTotalActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("ID");

        TfDelPro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(TfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnDel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TfDelPro, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDel, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(TfDelPro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TfTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        TfSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transparency.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbCustomer)
                            .addComponent(Lb2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LbCustomer)
                            .addComponent(cbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lb2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
    }// </editor-fold>//GEN-END:initComponents

    private static ArrayList<Vegetable> cart = new ArrayList<>();
    
    public static void ChangeCart(){
        cart = BillProductPanel.Cart;
        OrderBLL Or = new OrderBLL();
        BillView.pay.loadTable();
    }
    
    public static void reloadTable(){
        BillView.pay.loadTable();
    }
    
    private boolean isNum(String a){
        try{
            int s = Integer.parseInt(a);
            return true;
        }catch(NumberFormatException e){
            return false;
        }
    }
    
    private void initPayPane(){
        jLabel1.setForeground(Color.decode(ColorTheme.primary));
        btnPay.setBackground(Color.decode(ColorTheme.primary));
        btnPay.setForeground(Color.WHITE);
        btnDel.setBackground(Color.red);
        btnDel.setForeground(Color.white);
        
        TfSearch.getDocument().addDocumentListener(new DocumentListener(){
            @Override
            public void insertUpdate(DocumentEvent e) {
                Search();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                Search();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                Search();
            }
            
        });
          
        
        OrderBLL Or = new OrderBLL();
        List<Customers> cus = Or.loadcustomer();
        
        Object[] itemCbcus = Or.ConvertCusCb(cus);
        
        DefaultComboBoxModel modelcus = new DefaultComboBoxModel(itemCbcus);
        cbCustomer.setModel(modelcus);
    }
    
    private void loadTable(){
        OrderBLL Or = new OrderBLL();
        DefaultTableModel model = Or.convertVegetable(cart);
        jTable1.setModel(model);
        
        int total = 0;
        if(!cart.isEmpty()){
            for(int i = 0; i < cart.size(); i++){
                total += cart.get(i).getPrice();
            }
        }
        String t = String.valueOf(total);
        TfTotal.setText(t);
    }
    
    private void Search(){
        String timkiem = TfSearch.getText().trim();
        if(timkiem.isBlank()){
            loadtablewithoutchangeTotal(cart);
            return;
        }
        if(!cart.isEmpty()){
            List<Vegetable> result = new ArrayList<Vegetable>();
            for (Vegetable vegetable : cart) {
                if(vegetable.getVegetableName().toLowerCase().trim().contains(timkiem.toLowerCase())){
                    result.add(vegetable);
                }
            }
            loadtablewithoutchangeTotal(result);
        }
    }
    private void loadtablewithoutchangeTotal(List<Vegetable> list){
        OrderBLL or = new OrderBLL();
        DefaultTableModel model = or.convertVegetable(list);
        jTable1.setModel(model);
    }
    
//    private void UpdateIndexCart(){
//        for (int i = 0; i < cart.size(); i++) {
//            cart.get(i).setVegetableID(i+1);
//        }
//    }
    
    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        String DelID = TfDelPro.getText().trim();
        if(DelID.isBlank()){
            JOptionPane.showMessageDialog(this, "You didn't choose your product which you wanted to delete !!");
            return;
        }
        if(!isNum(DelID)){
            JOptionPane.showMessageDialog(this, "ID must be number");
            return;
        }
        
        int id = Integer.parseInt(DelID);
        boolean have = false;
        for(int i = 0; i < cart.size(); i++){
            if(cart.get(i).getVegetableID() == id){
                int result = JOptionPane.showConfirmDialog(this, "Sure to delete " + cart.get(i).getVegetableName());
                if(result == JOptionPane.YES_OPTION){
                    int amount = cart.get(i).getAmount();
                    for (Vegetable vegetable : BillView.prod.Product) {
                        if(vegetable.getVegetableID() == cart.get(i).getVegetableID()){
                            int ProductAmount = vegetable.getAmount();
                            vegetable.setAmount(amount+ProductAmount);
                            break;
                        }
                    }
                    cart.remove(i);
                    
                    JOptionPane.showMessageDialog(this, "Delete Successfully!!");
                    have = false;
                    break;
                }
            }
            else 
                have = true;
        }
        if(have){
            JOptionPane.showMessageDialog(this, "Delete Fail!!");
        }
        BillView.prod.reloadTable();
        loadTable();
    }//GEN-LAST:event_btnDelActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int index = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        
        String ID = model.getValueAt(index, 0).toString().trim();
        
        TfDelPro.setText(ID);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        BillView.pay.setVisible(false);
        BillView.prod.setVisible(true);
        BillView.order.setVisible(false);
        BillView.prod.reloadTable();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
        try{
            String tcus = cbCustomer.getSelectedItem().toString();
            String[] cus = tcus.split("\\.");

            float total = Float.parseFloat(TfTotal.getText());

            String note = TaNote.getText();

            long millis = System.currentTimeMillis();
            Date date = new Date(millis);
            
            if(cart.isEmpty()){
                JOptionPane.showMessageDialog(this, "You didn't get anything!!");
                return;
            }

            OrderBLL or = new OrderBLL();
            List<Customers> listcus = or.loadcustomer();
            Customers c = new Customers();
            for (Customers customers : listcus) {
                if(customers.getCustomerID() == Integer.parseInt(cus[0]) && customers.getFullname().equalsIgnoreCase(cus[1])){
                    c = customers;
                    break;
                }
            }

            List<Order> listorder = or.loadOrders();
            Order order = new Order();
            order.setDate(date);
            order.setNote(note);
            order.setTotal(total);
            order.setCustomer(c);
            order.setOrderID(listorder.size());
            
            ArrayList<Orderdetail> listorderdetail = new ArrayList<Orderdetail>();
            for (Vegetable ve : cart) {
                Orderdetail orderdetail = new Orderdetail();
                orderdetail.setOrder(order);
                orderdetail.setPrice(ve.getPrice());
                orderdetail.setQuantity(ve.getAmount());
                orderdetail.setVegetable(ve);
                orderdetail.setOrderID(order.getOrderID());
                orderdetail.setVegetableID(ve.getVegetableID());
                listorderdetail.add(orderdetail);
            }
            order.setListOrderDetail(listorderdetail);
            String resultadd = or.addOrder(order,order.getOrderID());
            if(resultadd.equals("Success")){
                for (Orderdetail orderdetail : listorderdetail) {
                    or.addOrderDetail(orderdetail);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Pay Fail!!");
                return;
            }
            List<Vegetable> vegetable = or.loadProducts();
            for (Vegetable vegeCart : cart) {
                for (Vegetable vegeHave : vegetable) {
                    if(vegeCart.getVegetableID() == vegeHave.getVegetableID()){
                        int oldquantity = vegeHave.getAmount();
                        int buyquantity = vegeCart.getAmount();
                        vegeHave.setAmount(oldquantity-buyquantity);
                        or.updateVegetable(vegeHave);
                        break;
                    }
                }
            }
            
            BillProductPanel.Cart.clear();
            ChangeCart();
            BillView.prod.changeProducts();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Pay Fail!!");
            return;
        }
        JOptionPane.showMessageDialog(this, "SuccessFully Pay!!");
    }//GEN-LAST:event_btnPayActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        BillView.pay.setVisible(false);
        BillView.prod.setVisible(false);
        BillView.order.setVisible(true);
        BillView.order.reloadTable();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void TfTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfTotalActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lb2;
    private javax.swing.JLabel LbCustomer;
    private javax.swing.JTextArea TaNote;
    private javax.swing.JTextField TfDelPro;
    private javax.swing.JTextField TfSearch;
    private javax.swing.JTextField TfTotal;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnPay;
    private javax.swing.JComboBox<String> cbCustomer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
