/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.shop_manager.GUI.view;

import com.mycompany.shop_manager.BLL.CategoryBLL;
import com.mycompany.shop_manager.DAL.Category;
import static com.mycompany.shop_manager.GUI.view.ImportView.cateview;
import static com.mycompany.shop_manager.GUI.view.ImportView.productview;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class CategoryViewPanel extends javax.swing.JPanel {
    
    CategoryBLL cb;
    DefaultTableModel model;
    int ID;

    /**
     * Creates new form CategoryViewPanel
     */
    public CategoryViewPanel() {
        initComponents();
        model=(DefaultTableModel) CategoryTable.getModel();
        showCategory();
    }
    public void showCategory(){
         try {
          cb=new CategoryBLL();
            cb.getCategories();
        } catch (Exception e) {
//            Logger.getLogger(Index.class.getName()).log(Level.SEVERE,null,e);
        }
        model.setRowCount(0);
        for(Category c : cb.getCategories()){
            model.addRow(new Object[]{
                c.getCategoryID(),c.getName(),c.getDescription()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_ContentTop = new javax.swing.JPanel();
        pnl_contentTopLeft = new javax.swing.JPanel();
        NameLb = new javax.swing.JLabel();
        MotaLb = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        MotaField = new javax.swing.JTextField();
        pnl_contentTopRight = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CategoryTable = new javax.swing.JTable();
        pnl_Header = new javax.swing.JPanel();
        DanhmucLb = new javax.swing.JLabel();
        SanphamLb = new javax.swing.JLabel();
        SeachField = new javax.swing.JTextField();
        SeachBtn = new javax.swing.JButton();

        NameLb.setText("Tên");

        MotaLb.setText("Mô tả");

        NameField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameFieldMouseClicked(evt);
            }
        });

        MotaField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MotaFieldMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_contentTopLeftLayout = new javax.swing.GroupLayout(pnl_contentTopLeft);
        pnl_contentTopLeft.setLayout(pnl_contentTopLeftLayout);
        pnl_contentTopLeftLayout.setHorizontalGroup(
            pnl_contentTopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contentTopLeftLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnl_contentTopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(MotaLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NameLb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pnl_contentTopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_contentTopLeftLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_contentTopLeftLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(MotaField)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        pnl_contentTopLeftLayout.setVerticalGroup(
            pnl_contentTopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contentTopLeftLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnl_contentTopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(pnl_contentTopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MotaLb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MotaField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        addBtn.setBackground(new java.awt.Color(0, 97, 255));
        addBtn.setText("Tạo dạnh mục ");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(255, 138, 0));
        updateBtn.setText("Cập nhật ");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 0, 46));
        deleteBtn.setText("Xóa danh mục ");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_contentTopRightLayout = new javax.swing.GroupLayout(pnl_contentTopRight);
        pnl_contentTopRight.setLayout(pnl_contentTopRightLayout);
        pnl_contentTopRightLayout.setHorizontalGroup(
            pnl_contentTopRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contentTopRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_contentTopRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        pnl_contentTopRightLayout.setVerticalGroup(
            pnl_contentTopRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contentTopRightLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_ContentTopLayout = new javax.swing.GroupLayout(pnl_ContentTop);
        pnl_ContentTop.setLayout(pnl_ContentTopLayout);
        pnl_ContentTopLayout.setHorizontalGroup(
            pnl_ContentTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ContentTopLayout.createSequentialGroup()
                .addComponent(pnl_contentTopLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_contentTopRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnl_ContentTopLayout.setVerticalGroup(
            pnl_ContentTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_contentTopRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_contentTopLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        CategoryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, ""},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Tên danh mục", "Mô tả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        CategoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoryTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CategoryTable);

        DanhmucLb.setText("Sản phẩm");
        DanhmucLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DanhmucLb.setPreferredSize(new java.awt.Dimension(56, 16));
        DanhmucLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DanhmucLbMouseClicked(evt);
            }
        });

        SanphamLb.setForeground(new java.awt.Color(102, 102, 255));
        SanphamLb.setText("Danh mục");
        SanphamLb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SanphamLb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SanphamLbMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_HeaderLayout = new javax.swing.GroupLayout(pnl_Header);
        pnl_Header.setLayout(pnl_HeaderLayout);
        pnl_HeaderLayout.setHorizontalGroup(
            pnl_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_HeaderLayout.createSequentialGroup()
                .addComponent(SanphamLb, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DanhmucLb, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_HeaderLayout.setVerticalGroup(
            pnl_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(DanhmucLb, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addComponent(SanphamLb, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        SeachBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-search-more-48.png"))); // NOI18N
        SeachBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SeachBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnl_ContentTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SeachField, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SeachBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SeachBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SeachField))))
                .addGap(25, 25, 25)
                .addComponent(pnl_ContentTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DanhmucLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DanhmucLbMouseClicked
        // TODO add your handling code here:
      cateview.setVisible(false);
      productview.setVisible(true);
    }//GEN-LAST:event_DanhmucLbMouseClicked

    private void SanphamLbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SanphamLbMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SanphamLbMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed

        // TODO add your handling code here:
        if(evt.getSource()==addBtn){
            int a=JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn thêm chứ!!");
            if(a==JOptionPane.YES_OPTION){
                   int id=-1;
                   for(Category c : cb.getCategories()){
                       if(c.getCategoryID()>id) id=c.getCategoryID();
                   }
                   Category cate=new Category();
                   cate.setCategoryID(id+1);
                   cate.setName(NameField.getText());
                   cate.setDescription(MotaField.getText());
                   if(NameField.getText().equals("")){
                       JOptionPane.showMessageDialog(null, "Lưu  không thành công vui lòng không để trống tên danh mục","Alert",JOptionPane.ERROR_MESSAGE);
                   }else{
                        cb.addCategory(cate);
                        JOptionPane.showMessageDialog(null, "Lưu thành công!", "Success", JOptionPane.INFORMATION_MESSAGE);        
                        showCategory();
                   }
            }
             
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
         if(evt.getSource()==deleteBtn){
            int a=JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn xóa chứ!!");
            if(a==JOptionPane.YES_OPTION){
                   Category cate=new Category();
                   cate.setCategoryID(ID);
                   cate.setName(NameField.getText());
                   cate.setDescription(MotaField.getText());
                    cb.deleteCategory(cate);
                    JOptionPane.showMessageDialog(null, "Xóa thành công!", "Success", JOptionPane.INFORMATION_MESSAGE);        
                    showCategory();
                 
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==updateBtn){
            int a=JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn sửa chứ!!");
            if(a==JOptionPane.YES_OPTION){
                   
                   Category cate=new Category();
                   cate.setCategoryID(ID);
                   cate.setName(NameField.getText());
                   cate.setDescription(MotaField.getText());
                   if(NameField.getText().equals("")){
                       JOptionPane.showMessageDialog(null, "Lưu  không thành công vui lòng không để trống tên danh mục","Alert",JOptionPane.ERROR_MESSAGE);
                   }else{
                        cb.updateCategory(cate);
                        JOptionPane.showMessageDialog(null, "Sửa thành công!", "Success", JOptionPane.INFORMATION_MESSAGE);        
                        showCategory();
                   }
            }
            
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void NameFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameFieldMouseClicked
        // TODO add your handling code here:
        NameField.setText("");
    }//GEN-LAST:event_NameFieldMouseClicked

    private void CategoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoryTableMouseClicked
        // TODO add your handling code here:
         int row=CategoryTable.getSelectedRow();
        ID=Integer.parseInt(CategoryTable.getModel().getValueAt(row, 0).toString());
        String name=CategoryTable.getModel().getValueAt(row, 1).toString();
        NameField.setText(name);
        String desctiption=CategoryTable.getModel().getValueAt(row, 2).toString();
        MotaField.setText(desctiption); 
    }//GEN-LAST:event_CategoryTableMouseClicked

    private void MotaFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MotaFieldMouseClicked
        // TODO add your handling code here:
        MotaField.setText("");
    }//GEN-LAST:event_MotaFieldMouseClicked

    private void SeachBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeachBtnMouseClicked
        // TODO add your handling code here:
        ArrayList<Category> catesearch=cb.SearchbyName(SeachField.getText());
        if(SeachField.getText().equals("")){
            showCategory();
        }
        else{
            model.setRowCount(0);
            for(Category c : catesearch){
            model.addRow(new Object[]{
                c.getCategoryID(),c.getName(),c.getDescription()
            });
        }
        }
       
        
    }//GEN-LAST:event_SeachBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CategoryTable;
    private javax.swing.JLabel DanhmucLb;
    private javax.swing.JTextField MotaField;
    private javax.swing.JLabel MotaLb;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLb;
    private javax.swing.JLabel SanphamLb;
    private javax.swing.JButton SeachBtn;
    private javax.swing.JTextField SeachField;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnl_ContentTop;
    private javax.swing.JPanel pnl_Header;
    private javax.swing.JPanel pnl_contentTopLeft;
    private javax.swing.JPanel pnl_contentTopRight;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
