/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.shop_manager.GUI.view;

import com.mycompany.shop_manager.BLL.CategoryBLL;
import com.mycompany.shop_manager.BLL.VegtableBLL;
import com.mycompany.shop_manager.DAL.Category;
import com.mycompany.shop_manager.DAL.Vegetable;
import static com.mycompany.shop_manager.GUI.view.ImportView.cateview;
import static com.mycompany.shop_manager.GUI.view.ImportView.productview;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class ProductViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductViewPanel
     */
    VegtableBLL vb;
    CategoryBLL cb;
    DefaultTableModel model;
    int ID;
    public ProductViewPanel() {
        initComponents();
        addCategoryselect();
        model=(DefaultTableModel) ProductTable.getModel();
       showVegetables();
    }
    public void addCategoryselect(){
         try {
          cb=new CategoryBLL();
          cb.getCategories();
          vb=new VegtableBLL();
          vb.getVegetables();
           for(Category c : cb.getCategories()){
            CategorySelect.addItem(c.getCategoryID()+"-"+c.getName());
            }
            this.add(CategorySelect);
        } catch (Exception e) {
            e.printStackTrace();
        }
         
    }
    public void showVegetables(){
         try {
          vb=new VegtableBLL();
            vb.getVegetables();
        } catch (Exception e) {
//            Logger.getLogger(Index.class.getName()).log(Level.SEVERE,null,e);
        }
        model.setRowCount(0);
        for(Vegetable v : vb.getVegetables()){
            model.addRow(new Object[]{
               v.getVegetableID(),v.getVegetableName(),v.getCatagoryID(),v.getUnit(),v.getAmount(),v.getImage(),v.getPrice()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ProductTable = new javax.swing.JTable();
        pnl_Header = new javax.swing.JPanel();
        lbl_headerProducts = new javax.swing.JLabel();
        lbl_headerStatistic = new javax.swing.JLabel();
        pnl_ContentTop = new javax.swing.JPanel();
        pnl_contentTopLeft = new javax.swing.JPanel();
        ImageLb = new javax.swing.JLabel();
        NameLb = new javax.swing.JLabel();
        PriceLb = new javax.swing.JLabel();
        AmountLb = new javax.swing.JLabel();
        CategoryLb = new javax.swing.JLabel();
        UnitLb = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        PriceField = new javax.swing.JTextField();
        AmountField = new javax.swing.JTextField();
        UnitField = new javax.swing.JTextField();
        CategorySelect = new javax.swing.JComboBox<>();
        ImageField = new javax.swing.JTextField();
        pnl_contentTopRight = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        SeachField = new javax.swing.JTextField();
        SeachBtn = new javax.swing.JButton();

        ProductTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên sản phẩm", "Danh mục", "Đơn vị", "Số lượng", "Ảnh", "Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ProductTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProductTable);

        lbl_headerProducts.setForeground(new java.awt.Color(51, 102, 255));
        lbl_headerProducts.setText("Sản phẩm");
        lbl_headerProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_headerProducts.setPreferredSize(new java.awt.Dimension(56, 16));
        lbl_headerProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_headerProductsMouseClicked(evt);
            }
        });

        lbl_headerStatistic.setText("Doanh mục");
        lbl_headerStatistic.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_headerStatistic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_headerStatisticMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_HeaderLayout = new javax.swing.GroupLayout(pnl_Header);
        pnl_Header.setLayout(pnl_HeaderLayout);
        pnl_HeaderLayout.setHorizontalGroup(
            pnl_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_HeaderLayout.createSequentialGroup()
                .addComponent(lbl_headerStatistic, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_headerProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_HeaderLayout.setVerticalGroup(
            pnl_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_headerProducts, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addComponent(lbl_headerStatistic, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        ImageLb.setText("Ảnh");

        NameLb.setText("Tên");

        PriceLb.setText("Giá");

        AmountLb.setText("Số lượng");

        CategoryLb.setText("Danh mục");

        UnitLb.setText("Đơn vị");

        CategorySelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategorySelectActionPerformed(evt);
            }
        });

        ImageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImageFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_contentTopLeftLayout = new javax.swing.GroupLayout(pnl_contentTopLeft);
        pnl_contentTopLeft.setLayout(pnl_contentTopLeftLayout);
        pnl_contentTopLeftLayout.setHorizontalGroup(
            pnl_contentTopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contentTopLeftLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_contentTopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_contentTopLeftLayout.createSequentialGroup()
                        .addComponent(ImageLb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ImageField, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_contentTopLeftLayout.createSequentialGroup()
                        .addComponent(PriceLb)
                        .addGap(18, 18, 18)
                        .addComponent(PriceField))
                    .addGroup(pnl_contentTopLeftLayout.createSequentialGroup()
                        .addComponent(NameLb)
                        .addGap(18, 18, 18)
                        .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(pnl_contentTopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_contentTopLeftLayout.createSequentialGroup()
                        .addComponent(AmountLb)
                        .addGap(18, 18, 18)
                        .addComponent(AmountField))
                    .addGroup(pnl_contentTopLeftLayout.createSequentialGroup()
                        .addGroup(pnl_contentTopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CategoryLb)
                            .addComponent(UnitLb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_contentTopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CategorySelect, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(UnitField))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        pnl_contentTopLeftLayout.setVerticalGroup(
            pnl_contentTopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contentTopLeftLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnl_contentTopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ImageLb)
                    .addComponent(AmountLb)
                    .addComponent(AmountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ImageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(pnl_contentTopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameLb)
                    .addComponent(CategoryLb)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CategorySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnl_contentTopLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceLb)
                    .addComponent(UnitLb)
                    .addComponent(PriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UnitField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        addBtn.setBackground(new java.awt.Color(0, 97, 255));
        addBtn.setText("Tạo sản phẩm");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(255, 138, 0));
        updateBtn.setText("Cập nhật ");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(255, 0, 46));
        deleteBtn.setText("Xóa sản phẩm");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_contentTopRightLayout = new javax.swing.GroupLayout(pnl_contentTopRight);
        pnl_contentTopRight.setLayout(pnl_contentTopRightLayout);
        pnl_contentTopRightLayout.setHorizontalGroup(
            pnl_contentTopRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contentTopRightLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_contentTopRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addGap(0, 36, Short.MAX_VALUE))
        );
        pnl_contentTopRightLayout.setVerticalGroup(
            pnl_contentTopRightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contentTopRightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnl_ContentTopLayout = new javax.swing.GroupLayout(pnl_ContentTop);
        pnl_ContentTop.setLayout(pnl_ContentTopLayout);
        pnl_ContentTopLayout.setHorizontalGroup(
            pnl_ContentTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ContentTopLayout.createSequentialGroup()
                .addComponent(pnl_contentTopLeft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_contentTopRight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        pnl_ContentTopLayout.setVerticalGroup(
            pnl_ContentTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_contentTopRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnl_contentTopLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        SeachBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-search-more-48.png"))); // NOI18N
        SeachBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SeachBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnl_ContentTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SeachField, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SeachBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SeachField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SeachBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addComponent(pnl_ContentTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_headerProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_headerProductsMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_lbl_headerProductsMouseClicked

    private void lbl_headerStatisticMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_headerStatisticMouseClicked
        // TODO add your handling code here:
        cateview.setVisible(true);
        productview.setVisible(false);
    }//GEN-LAST:event_lbl_headerStatisticMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
          if(evt.getSource()==addBtn){
            int a=JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn thêm chứ!!");
            if(a==JOptionPane.YES_OPTION){
                   int id=-1;
                   for(Vegetable v : vb.getVegetables()){
                       if(v.getVegetableID()>id) id=v.getVegetableID();
                   }
                   Vegetable veget=new Vegetable();
                   veget.setVegetableID(id+1);
                   veget.setVegetableName(NameField.getText());
                   veget.setAmount(Integer.parseInt(AmountField.getText()));
                   veget.setUnit(UnitField.getText());
                   veget.setImage(ImageField.getText());
                   veget.setPrice(Float.parseFloat(PriceField.getText()));
                   String selectedItem=(String) CategorySelect.getSelectedItem();
                   String[] getid=selectedItem.split("-");
                   System.out.println("getid");
                   veget.setCatagoryID(Integer.parseInt(getid[0]));
                   if(NameField.getText().equals("")||UnitField.getText().equals("")
                           ||ImageField.getText().equals("")||Integer.parseInt(AmountField.getText())<1||Float.parseFloat(PriceField.getText())<=0){
                       JOptionPane.showMessageDialog(null, "Lưu  không thành công  không để trống hoặc nhập sai giá trị","Alert",JOptionPane.ERROR_MESSAGE);
                   }else{
                        vb.addVegetable(veget);
                        JOptionPane.showMessageDialog(null, "Lưu thành công!", "Success", JOptionPane.INFORMATION_MESSAGE);        
                        showVegetables();
                   }
            }
             
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
          if(evt.getSource()==deleteBtn){
            int a=JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn xóa chứ!!");
            if(a==JOptionPane.YES_OPTION){
                   Vegetable veget=new Vegetable();
                   veget.setVegetableID(ID);
                   veget.setVegetableName(NameField.getText());
                   veget.setAmount(Integer.parseInt(AmountField.getText()));
                   veget.setUnit(UnitField.getText());
                   veget.setImage(ImageField.getText());
                   veget.setPrice(Float.parseFloat(PriceField.getText()));
                   String selectedItem=(String) CategorySelect.getSelectedItem();
                   String[] getid=selectedItem.split("-");
                   System.out.println("getid");
                   veget.setCatagoryID(Integer.parseInt(getid[0]));
                    vb.deleteVegetable(veget);
                    JOptionPane.showMessageDialog(null, "Xóa thành công!", "Success", JOptionPane.INFORMATION_MESSAGE);        
                    showVegetables();
                 
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void ImageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImageFieldActionPerformed

    private void CategorySelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategorySelectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategorySelectActionPerformed

    private void ProductTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductTableMouseClicked
        // TODO add your handling code here:
         int row=ProductTable.getSelectedRow();
        ID=Integer.parseInt(ProductTable.getModel().getValueAt(row, 0).toString());
        String name=ProductTable.getModel().getValueAt(row, 1).toString();
        NameField.setText(name);
        String categoryid=ProductTable.getModel().getValueAt(row, 2).toString();
        CategorySelect.setSelectedItem(categoryid+"-"+cb.SeachByID(Integer.parseInt(categoryid)));
        System.out.println(categoryid+"-"+cb.SeachByID(Integer.parseInt(categoryid)));
        CategorySelect.revalidate();
        String unit=ProductTable.getModel().getValueAt(row, 3).toString();
        UnitField.setText(unit);
        String amount=ProductTable.getModel().getValueAt(row, 4).toString();
        AmountField.setText(amount);
        String image=ProductTable.getModel().getValueAt(row, 5).toString();
        ImageField.setText(image);
        String price=ProductTable.getModel().getValueAt(row, 6).toString();
        PriceField.setText(price);
    }//GEN-LAST:event_ProductTableMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
         if(evt.getSource()==updateBtn){
            int a=JOptionPane.showConfirmDialog(null,"Bạn có chắc muốn sửa chứ!!");
            if(a==JOptionPane.YES_OPTION){
                   
                    Vegetable veget=new Vegetable();
                   veget.setVegetableID(ID);
                   veget.setVegetableName(NameField.getText());
                   veget.setAmount(Integer.parseInt(AmountField.getText()));
                   veget.setUnit(UnitField.getText());
                   veget.setImage(ImageField.getText());
                   veget.setPrice(Float.parseFloat(PriceField.getText()));
                   String selectedItem=(String) CategorySelect.getSelectedItem();
                   String[] getid=selectedItem.split("-");
                   System.out.println("getid");
                   veget.setCatagoryID(Integer.parseInt(getid[0]));
                    if(NameField.getText().equals("")||UnitField.getText().equals("")
                           ||ImageField.getText().equals("")||Integer.parseInt(AmountField.getText())<1||Float.parseFloat(PriceField.getText())<=0){
                       JOptionPane.showMessageDialog(null, "Lưu  không thành công  không để trống hoặc nhập sai giá trị","Alert",JOptionPane.ERROR_MESSAGE);
                   }else{
                        vb.updateVegetable(veget);
                        JOptionPane.showMessageDialog(null, "Lưu thành công!", "Success", JOptionPane.INFORMATION_MESSAGE);        
                        showVegetables();
                   }
            }
            
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void SeachBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeachBtnMouseClicked
        // TODO add your handling code here:
          ArrayList<Vegetable> vegetsearch=vb.SearchbyName(SeachField.getText());
        if(SeachField.getText().equals("")){
            showVegetables();
        }
        else{
            model.setRowCount(0);
            for(Vegetable v : vegetsearch){
            model.addRow(new Object[]{
               v.getVegetableID(),v.getVegetableName(),v.getCatagoryID(),v.getUnit(),v.getAmount(),v.getImage(),v.getPrice()
            });
        
        }
        }
    }//GEN-LAST:event_SeachBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AmountField;
    private javax.swing.JLabel AmountLb;
    private javax.swing.JLabel CategoryLb;
    private javax.swing.JComboBox<String> CategorySelect;
    private javax.swing.JTextField ImageField;
    private javax.swing.JLabel ImageLb;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel NameLb;
    private javax.swing.JTextField PriceField;
    private javax.swing.JLabel PriceLb;
    private javax.swing.JTable ProductTable;
    private javax.swing.JButton SeachBtn;
    private javax.swing.JTextField SeachField;
    private javax.swing.JTextField UnitField;
    private javax.swing.JLabel UnitLb;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_headerProducts;
    private javax.swing.JLabel lbl_headerStatistic;
    private javax.swing.JPanel pnl_ContentTop;
    private javax.swing.JPanel pnl_Header;
    private javax.swing.JPanel pnl_contentTopLeft;
    private javax.swing.JPanel pnl_contentTopRight;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
